### ISSUE TITLE
Bottom Navigation Bar

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/Musgenix#1]
Make bottom navigation bar for songs, albums, favorite and playlists.

**Comment by afreenabegum** [comment]
Hey @Kajal13081 , I am interested in contributing to this issue.
But can you explain do we need to write the script and submit it.

Thanks
Afreena.

**Comment by Kajal13081** [comment]
Hey @afreenabegum , No you don't have to writt any script. You have to only fix the issue and make PR.

**Comment by afreenabegum** [comment]
> Hey @afreenabegum , No you don't have to writt any script. You have to only fix the issue and make PR. 

Please assign it to me. I am interested in contribute to this issue. 
If I need any help. I'll ping u. 

Thanks.

**Comment by Kajal13081** [comment]
Working on any issue will start from Feb 1. So I will assign you then. For now go through the project and understand the code base. If you want you can check issue #4. That's very important to fix.

**Comment by afreenabegum** [comment]
Okay. 
Thank you for informing.

**Comment by pree-T** [comment]
May I work on this? @Kajal13081

**Comment by shubhanshu-coder** [comment]
can i work on this ?
@Kajal13081

**Comment by shubhanshu-coder** [comment]
can i work on this ?
@Kajal13081

**Comment by Kajal13081** [comment]
@afreenabegum assigned. All the best:)

**Comment by Kajal13081** [comment]
@pree-T @shubhanshu-coder issues will be assigned on first come service. Please go through other issues. If the assignee isn't able to make PR in assigned time, next person will be assigned. 
Happy Coding:)

**Comment by afreenabegum** [comment]
> @afreenabegum assigned. All the best:) 

I'll work on it. Thank you.

**Comment by afreenabegum** [comment]
@Kajal13081 
where we need to make the changes in Layout section?

**Comment by Kajal13081** [comment]
> @Kajal13081 where we need to make the changes in Layout section?

I will let you know once issue #4 get merged. You will be given extra time for this issue.
Basically we need to make 3-4 fragments for album, playlist, favourites and songs. The song list should be in song fragment.

**Comment by afreenabegum** [comment]
ok then !! Do let me know if that issue is merged.

> > @Kajal13081 where we need to make the changes in Layout section?
> 
> I will let you know once issue #4 get merged. You will be given extra time for this issue. Basically we need to make 3-4 fragments for album, playlist, favourites and songs. The song list should be in song fragment.

**Comment by afreenabegum** [comment]
@Kajal13081 
How many days it will take for that issue?

**Comment by Kajal13081** [comment]
> @Kajal13081 How many days it will take for that issue?

PR has been raised already. I need to review it and merge. Will do it by today only. I am outside rn.

**Comment by afreenabegum** [comment]
> > @Kajal13081 How many days it will take for that issue?
> 
> PR has been raised already. I need to review it and merge. Will do it by today only. I am outside rn.

Ok please try to verify it. I too need some time for my issue .I have exams from tomorrow 
small request from my side, ASAP if you verify that. I can start my issue by evening.

**Comment by Kajal13081** [comment]
I merged it. You update your project and then resume your work.

**Comment by Kajal13081** [comment]
@afreenabegum you can work now.
