### ISSUE TITLE
Design logo for the app

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/Musgenix#10]
Design a logo for the app. It should be your own. You can take help/idea from google but don't copy it.

**Comment by Shreyan-12345** [comment]
i want to work on this

**Comment by Kajal13081** [comment]
I will assign it to you tomorrow @Shreyan-12345

**Comment by Shreyan-12345** [comment]
ok @Kajal13081

**Comment by Kajal13081** [comment]
@Shreyan-12345 you are assigned. All the best😀

**Comment by Shreyan-12345** [comment]
thanks @Kajal13081 within 24 hours i have to submit?

**Comment by vilgad** [comment]
> thanks @Kajal13081 within 24 hours i have to submit?

yes, All the BEST

**Comment by Shreyan-12345** [comment]
can I get 1 day extra time plz @Kajal13081 , some unavoidable issue plzzzzz

**Comment by Kajal13081** [comment]
> can I get 1 day extra time plz @Kajal13081 , some unavoidable issue plzzzzz

okay sure.

**Comment by Shreyan-12345** [comment]
i will submit is today @Kajal13081

**Comment by Shreyan-12345** [comment]
didi , you haven't merged yet ??????
