### ISSUE TITLE
Feature to delete song from song list by swiping the song card

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/Musgenix#14]
Add a feature to delete multiple songs from song list.

**Comment by sarkartanmay393** [comment]
Hello , I am Tanmay Sarkar. I want to solve this issue. Kindly Assign me this.

**Comment by shubhanshu-coder** [comment]
Can i work in this issue under JWOC?

**Comment by Kajal13081** [comment]
Sure. Assigned @shubhanshu-coder
