### ISSUE TITLE
Fetch the song icon in song list

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/Musgenix#18]
The song icon has only a music pic for now. Fetch the song icon from the list of the song.

**Comment by ShresthaBanerjee01** [comment]
Hello, I am Shrestha Banerjee. I want to work on this issue. Could you assign it to me?

**Comment by Kajal13081** [comment]
Assigned @ShresthaBanerjee01. All the best.

**Comment by Kajal13081** [comment]
@ShresthaBanerjee01 what's the update?

**Comment by Kajal13081** [comment]
I am removing you as assignee @ShresthaBanerjee01

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC

**Comment by Kajal13081** [comment]
Assigned @binayshaw7777
