### ISSUE TITLE
Sort songs

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/Musgenix#2]
Add features to sort songs by date, A-Z, Z-A etc

**Comment by Pdahiya5033** [comment]
I would like to add this feature

**Comment by Shreyan-12345** [comment]
sorting means to sort in lexicographically?

**Comment by Kajal13081** [comment]
@Shreyan-12345 you can sort songs by the duration of song, their names(in ascending and in descending) and by date.

**Comment by Pdahiya5033** [comment]
I would like to contribute to this issue

**Comment by Kajal13081** [comment]
@Pdahiya5033 assigned. Happy Coding:)
