### ISSUE TITLE
Search Songs

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/Musgenix#3]
Add a feature to search songs. Use material design to design the UI.

**Comment by Pdahiya5033** [comment]
I would like to add this feature

**Comment by Kajal13081** [comment]
Sure @Pdahiya5033. I will assign it to you.

**Comment by Kajal13081** [comment]
@Pdahiya5033 you have been assigned two issues. First complete them then I'll assign to you next. 
All the best😀

**Comment by raxvab** [comment]
I want to work with this issue under JWOC

**Comment by Kajal13081** [comment]
@raxvab updates?

**Comment by raxvab** [comment]
Please unassign me as I'm not able to work with Android studio in my local machine.

**Comment by Kajal13081** [comment]
@Pdahiya5033 would you like to work on this issue?

**Comment by Pdahiya5033** [comment]
I will work but you have to unassign that folders issue @Kajal13081

**Comment by shubhanshu-coder** [comment]
Can i work ok this issue under JWOC?

**Comment by Kajal13081** [comment]
Assigning to @shubhanshu-coder. All the best.

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC.
If it's not completed yet.

**Comment by Kajal13081** [comment]
Assigned @binayshaw7777
