### ISSUE TITLE
Songs list is not displayed

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/Musgenix#4]
I have connected recyclerView and adapter. But song list isn't displaying on phone screen. 
Error is adapter not set. 
Try to debug the app and fix the error.

**Comment by aritra-tech** [comment]
Hey @Kajal13081, I am interested in contributing to this issue.

Thanks
Aritra

**Comment by Kajal13081** [comment]
Hey @aritra-tech, contribution will start from 1st Feb. For now understand the code base and try to find more features which could be implemented.

**Comment by Pdahiya5033** [comment]
I am interested in contributing to this project 🙂

**Comment by aritra-tech** [comment]
> Hey @aritra-tech, contribution will start from 1st Feb. For now understand the code base and try to find more features which could be implemented.

oK @Kajal13081

**Comment by Kajal13081** [comment]
@Pdahiya5033 you have been assigned. All the best:)
