### ISSUE TITLE
Make PlayerView

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/Musgenix#5]
Make a clean UI of PlayerView using material design with proper functionality and theme should be same for all screens.
On clicking any song, the playerView should open.

**Comment by shubhankar-bt** [comment]
Hey, I am interested to work in this issue

**Comment by shubhankar-bt** [comment]
> I will assign it to you @shubhankar-bt tomorrow.

ok thankyou

**Comment by shubhankar-bt** [comment]
I am interested to work in this issue JWOC

**Comment by Kajal13081** [comment]
Assigned @shubhankar-bt . 
Make the playerView functional. When we click on any song it should open the player and take care of theme. 
All the best;)

**Comment by shubhankar-bt** [comment]
Hey @Kajal13081  can you give me a basic idea about the theme??

**Comment by Kajal13081** [comment]
See the color code in xml file. Use that color code or somewhat similar color.

**Comment by Pdahiya5033** [comment]
I would like to add this feature under jwoc
