### ISSUE TITLE
Add animated splash screen

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/Musgenix#6]
Make an animated splash screen with nice logo. Take care of color themes.

**Comment by aritra-tech** [comment]
Hey @Kajal13081, I am interested in contributing to this issue.

**Comment by Kajal13081** [comment]
Sure, I will assign it to you on 1st Feb.

**Comment by aritra-tech** [comment]
Ok thanks

**Comment by Kajal13081** [comment]
@pree-T sure but its on first come service so someone have already asked first. I will make more issues. For now go through other issues.

**Comment by Kajal13081** [comment]
You have been assigned @aritra-tech . All the best:)
