### ISSUE TITLE
Add feature to share songs

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/Musgenix#8]

**Comment by raxvab** [comment]
I want to work with this issue under JWOC.
Can i get a bit of guidance while doing so?

**Comment by Kajal13081** [comment]
Sure @raxvab. You can use intent to share the song with others. If any help needed do ask me. 
All the best.

**Comment by Kajal13081** [comment]
@raxvab updates?

**Comment by raxvab** [comment]
Please unassign me as I'm not able to work with Android studio in my local machine.

**Comment by shubhanshu-coder** [comment]
Can i work on this under Jwoc? @Kajal13081

**Comment by Kajal13081** [comment]
@shubhanshu-coder you have been assigned 2 issues already. First finish them then I will assign it to you. All the best.

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC

**Comment by Kajal13081** [comment]
Assigned @binayshaw7777
