### ISSUE TITLE
Add feature to use song as ringtone

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/Musgenix#9]
Add feature to use song as phone ringtone, alarm tone.
You could take help from google and stackoverflow to set audio files as ringtones.

**Comment by ken1000minus7** [comment]
Hello, I would like to try working on this issue. How exactly do you want the option for setting ringtone to appear? Like should it appear when the user long presses the music card or should there be an option within the card?

**Comment by Kajal13081** [comment]
Sure @ken1000minus7 . I think we can provide an option within the card. We'll use the long press feature for other purpose when we will be connecting the project with Firebase. 
I am assigning you. All the best:) 
If any doubt please do contact me.
